Add optional boolean value to all store_true instances
fox-it/acquire pull request #179
Opened 2024-07-05 10:56 UTC by Miauwkeru

2024-07-10 09:53 UTC, Schamper commented on acquire/utils.py
> +    parser.add_argument("--no-log", action=argparse.BooleanOptionalAction, help=argparse.SUPPRESS)
How will this work? —no-no-log?

2024-07-10 09:53 UTC, Schamper commented on acquire/utils.py
> +        "--disable-report", action=argparse.BooleanOptionalAction, help="disable acquisition report file"
Same here, no-disable-report?

2024-07-10 09:53 UTC, Schamper commented on acquire/utils.py
> +    parser.add_argument("--no-proxy", action=argparse.BooleanOptionalAction, help="don't autodetect proxies")
Same question.

2024-07-18 11:24 UTC, Poeloe requested changes

2024-07-18 11:24 UTC, Poeloe commented on acquire/acquire.py
>      help="Skip collection of data files in the Recycle Bin",
Shouldn't this help message change now as well?

2024-07-18 12:20 UTC, Poeloe requested changes

2024-07-18 12:20 UTC, Poeloe commented on acquire/acquire.py
> +        if cli_args.data_files is None and cli_args.data_files:
If it's `None` then `cli_args.data_files` evaluates to `False`, so I guess you mean `or` here?

2024-07-18 12:28 UTC, Poeloe approved these changes
Now really: LGTM!

2024-07-18 12:29 UTC, Schamper requested changes

2024-07-18 12:29 UTC, Schamper commented on acquire/acquire.py
> +        if cli_args.data_files is None or cli_args.data_files:
I assume `data_files` will be `None` if no argument is given? So that the default behaviour stayed the same (collect data files)?

2024-07-18 12:39 UTC, Schamper approved these changes

2024-07-18 12:40 UTC, merged