Add collection of Docker logs
fox-it/acquire pull request #199
Opened 2024-11-01 12:28 UTC by Paradoxis

Added docker logs, hostname and container configs to acquire and included it in the `FULL` Linux profile

2024-11-01 13:25 UTC, Horofic requested changes

2024-11-01 13:25 UTC, Horofic commented on acquire/acquire.py
>      SPEC = [
Could you add a description (`DESC`), like the other modules.

2024-11-01 13:27 UTC, Horofic commented on acquire/acquire.py
> +        Docker,
This can should also be added to the `WindowsProfile`

2024-11-01 13:39 UTC, Schamper requested changes

2024-11-01 13:39 UTC, Schamper commented on acquire/acquire.py
> +class Docker(Module):
```suggestion
class Docker(Module):
    DESC = "various Docker logs and configuration files"
```

2024-11-01 15:46 UTC, Horofic approved these changes

2024-11-04 09:18 UTC, Schamper approved these changes

2024-11-04 09:19 UTC, merged