Make collection report consistent
fox-it/acquire pull request #75
Opened 2023-07-07 13:07 UTC by Miauwkeru

(DIS-1935)

2023-07-10 07:54 UTC, Schamper requested changes

2023-07-10 07:54 UTC, Schamper commented on acquire/acquire.py
> +        ("glob", "sysvol/Users*/AppData/Local/F-Secure/Log"),
Why not make this use from_user_home too?

2023-07-10 07:54 UTC, Schamper commented on acquire/acquire.py
> +        ("glob", "sysvol/Users*/AppData/Roaming/Malwarebytes/Malwarebytes Anti-Malware/Logs"),
Why not make this use from_user_home too?

2023-07-10 13:29 UTC, Poeloe requested changes

2023-07-10 13:29 UTC, Poeloe commented on tests/test_collector.py
> +    target = create_target_with_files(tmp_path, create_paths)
Why not using the mock_target within the conftest?

2023-07-11 09:42 UTC, Poeloe commented on tests/test_collector.py
> +        ("file", "collect/this/file", 1, ["collect/this/file"]),
For consistency, also put al the values of this tuple on separate lines

2023-07-17 09:20 UTC, pyrco requested changes
I'd rename the `test_glob.py`  to something more descriptive and more in line with how we want to call our unittest, like `test_acquire_modules.py`.

2023-07-17 09:20 UTC, pyrco commented on acquire/acquire.py
>          ("dir", "sysvol/Users/All Users/Application Data/McAfee/DesktopProtection"),
This one can also use `from_user_home`

2023-07-18 07:49 UTC, pyrco approved these changes

2023-07-18 08:14 UTC, merged