Add option to collect private ssh keys
fox-it/acquire pull request #78
Opened 2023-07-18 11:52 UTC by Miauwkeru

- Iterate over `/Users/*` in from_user_home for osx
- Create file_filter inside the collector
- Use a context manager to bind the module
- Add python test modules and stuff
(DIS-1869)

2023-07-18 12:12 UTC, Zawadidone commented
> @Zawadidone I did change the ssh code a lil bit more here. ':) To allow for a filter option

Nice work! FYI I am currently working on this https://github.com/fox-it/dissect.target/issues/300.

2023-07-19 09:02 UTC, pyrco reviewed
Could you split this change set in 3 commits (and not squash them on merge):
- the new/stub `from_user_home()` changes
- the `collector.bind_module()` changes
-  the ssh private keys & file filter changes

As they are changes in different sets of fucntionality.

2023-07-19 10:56 UTC, pyrco commented on acquire/acquire.py
> +        return
Would it be an idea to split this off into a `misc_osx_user_homes()`, similar as for windows? I think we also want to iterate over `/Users/*` (and `/home/*` and `/root` for other Unixes), same as we do for windows, irrespective of what comes back from `user_details()`

2023-07-19 13:37 UTC, pyrco requested changes

2023-07-19 14:15 UTC, pyrco approved these changes

2023-07-19 14:27 UTC, merged